# Google Analytics
google-ID: 'UA-27168505-1'

# Menu items
menu:
- {name: 'Home', url: '/'}
- {name: 'Photos', url: '/photos/'}
- {name: 'About', url: '/about/'}

# Social icons
social:
- {icon: 'twitter', link: 'https://twitter.com/dmvaldman'}
- {icon: 'github', link: 'https://www.github.com/dmvaldman'}

# Pagination settings
pagination:
  projects: 5
  writing: 5
  next_page: 'Newer'
  previous_page: 'Older'

# Post date prefix
post_date_prefix: 'Written on'

# Collections
collections:
  writing:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /:name/
  drafts:
    output: true
    permalink: /drafts/:name/
  photography:
    output: false

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Writings'
description:	       ''
author:              'David Valdman'
twitter_username:    'dmvaldman'

# Configure jekyll-feed to use writing collection
feed:
  collections:
    - writing

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "draft"