# Site Build Settings

# Pagination settings
pagination:
  projects: 5
  writing: 5

# Collections
collections:
  writing:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /:name/
  drafts:
    output: true
    permalink: /drafts/:name/
  photography:
    output: false

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Writings'
description:	       ''
author:              'David Valdman'
twitter_username:    'dmvaldman'

# Configure jekyll-feed to use writing collection
feed:
  collections:
    - writing

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "draft"