# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-27168505-1'

menu:
- {name: 'Writing', path: 'menu', url: '../'}
- {name: 'Photos', path: 'menu', url: 'photography.html'}
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/dmvaldman'}
- {icon: 'twitter', link: 'https://twitter.com/dmvaldman'}
- {icon: 'envelope', link: 'mailto:dmvaldman@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: ''

related_posts: 'Related posts:'

post_date_prefix: 'Written on'
